apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fastlegerest
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: fastlegerest/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: fastlegerest/internal/isReady
    initialDelay: 120
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: fastlegerest/internal/prometheus
  ingresses:
    - "https://fastlegerest.nais.adeo.no"
    - "https://app.adeo.no/fastlegerest"
  vault:
    enabled: true
    paths:
      - kvPath: "/azuread/data/prod/creds/fastlegerest"
        mountPath: "/secrets/azuread/fastlegerest"
      - kvPath: "/serviceuser/data/prod/srvfastlegerest"
        mountPath: "/secrets/serviceuser/fastlegerest"
      - kvPath: "/kv/prod/fss/fastlegerest/default"
        mountPath: "/secrets/vault"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: '443'
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: 'true'
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: EKSTERN_HELSE_FASTLEGEINFORMASJON_URL
      value: https://pep-gw.oera.no:9443/ekstern/helse/fastlegeinformasjon
    - name: EKSTERN_HELSE_ADRESSEREGISTERET_V1_URL
      value: https://pep-gw.oera.no:9443/ekstern/helse/adresseregisteret/v1
    - name: VIRKSOMHET_BRUKERPROFIL_V3_URL
      value: https://wasapp.adeo.no/tpsws/Brukerprofil_v3
    - name: PARTNER_WS_URL
      value: https://wasapp.adeo.no/emottak-partnerweb/partnerService/
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll/api/tilgang
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: NO_NAV_SECURITY_OIDC_ISSUER_STS_DISCOVERYURL
      value: http://security-token-service/rest/v1/sts/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_OIDC_ISSUER_STS_ACCEPTEDAUDIENCE
      value: srvsyfooppfolgings
    - name: NO_NAV_SECURITY_OIDC_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_OIDC_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 9b4e07a3-4f4c-4bab-b866-87f62dff480d,97085f8d-2aa8-4a4e-ba8c-10bcc5691191
    - name: AD_ACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: SYFOPARTNERINFO_APPID
      value: 55732aaa-9976-4a7b-8342-2e502a3cdce4
