apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fastlegerest
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: fastlegerest/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: fastlegerest/internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: fastlegerest/internal/prometheus
  ingresses:
    - "https://fastlegerest.dev.intern.nav.no"
    - "https://fastlegerest.nais.preprod.local"
    - "https://app-q1.adeo.no/fastlegerest"
  vault:
    enabled: true
    paths:
      - kvPath: "/azuread/data/dev/creds/fastlegerest"
        mountPath: "/secrets/azuread/fastlegerest"
      - kvPath: "/serviceuser/data/dev/srvfastlegerest"
        mountPath: "/secrets/serviceuser/fastlegerest"
      - kvPath: "/kv/preprod/fss/fastlegerest/default"
        mountPath: "/secrets/vault"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: '443'
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: 'true'
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: EKSTERN_HELSE_FASTLEGEINFORMASJON_URL
      value: https://pep-gw-q4.oera-q.local:9443/ekstern/helse/fastlegeinformasjon
    - name: EKSTERN_HELSE_ADRESSEREGISTERET_V1_URL
      value: https://pep-gw-q4.oera-q.local:9443/ekstern/helse/adresseregisteret/v1
    - name: PARTNER_WS_URL
      value: https://wasapp-q1.adeo.no/emottak-partnerweb/partnerService/
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
    - name: AZUREAD_TENANT_ID
      value: "966ac572-f5b7-4bbe-aa88-c76419c0f851"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "32e36aa5-1d12-452a-9b1e-9f3f557cbb4d"
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_DISCOVERYURL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_ACCEPTEDAUDIENCE
      value: srvsyfooppfolgings
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 38e07d31-659d-4595-939a-f18dce3446c5,595e0237-37db-4d5e-8dde-4fb3d0bf8839,33ad42cc-b88c-45c9-b640-8c8a4c93d3a1
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_DISCOVERYURL
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration"
    - name: AD_ACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: SYFOPARTNERINFO_APPID
      value: 077b7904-dec5-4d2e-bf69-bb17f56658c2
    - name: SYFOPARTNERINFO_URL
      value: "https://syfopartnerinfo.dev.intern.nav.no"
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
