apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fastlegerest
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: fastlegerest/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: fastlegerest/internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: fastlegerest/internal/prometheus
  ingresses:
    - "https://fastlegerest.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-fss
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
        - host: "syfopartnerinfo.dev-fss-pub.nais.io"
        - host: "isproxy.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
      rules:
        - application: isdialogmelding
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://fastlegerest.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.dev-fss-pub.nais.io/syfo-tilgangskontroll/api/tilgang
    - name: SYFOPARTNERINFO_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfopartnerinfo"
    - name: SYFOPARTNERINFO_URL
      value: "https://syfopartnerinfo.dev-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: ISDIALOGMELDING_IDENTIFIER
      value: dev-gcp.teamsykefravr.isdialogmelding
    - name: ISDIALOGMELDING_URL
      value: https://isdialogmelding.dev.intern.nav.no
    - name: ISPROXY_CLIENT_ID
      value: dev-fss.teamsykefravr.isproxy
    - name: ISPROXY_URL
      value: https://isproxy.dev-fss-pub.nais.io
