apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fastlegerest
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://fastlegerest.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-fss
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: dev-gcp
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
        - host: "isproxy.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://fastlegerest.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  env:
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.dev-fss-pub.nais.io/syfo-tilgangskontroll/api/tilgang
    - name: PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: ISPROXY_CLIENT_ID
      value: dev-fss.teamsykefravr.isproxy
    - name: ISPROXY_URL
      value: https://isproxy.dev-fss-pub.nais.io
