apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fastlegerest
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://fastlegerest.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: prod-fss
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "syfo-tilgangskontroll.prod-fss-pub.nais.io"
        - host: "isproxy.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: fastlegerest-redis
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://fastlegerest.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: fastlegerest-redis-password
  env:
    - name: REDIS_HOST
      value: "fastlegerest-redis.teamsykefravr.svc.cluster.local"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: ISPROXY_CLIENT_ID
      value: "prod-fss.teamsykefravr.isproxy"
    - name: ISPROXY_URL
      value: "https://isproxy.prod-fss-pub.nais.io"
