apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fastlegerest
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 5m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://fastlegerest.intern.dev.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
        - application: finnfastlege
        - application: isdialogmelding
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "ws.test.nhn.no"
      rules:
        - application: fastlegerest-redis
        - application: istilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: fastlegerest-redis-password
    - secret: fastlegerest-nhn-serviceuser
  env:
    - name: REDIS_HOST
      value: "fastlegerest-redis.teamsykefravr.svc.cluster.local"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: FASTLEGE_URL
      value: "https://ws.test.nhn.no/v2/flr/Basic"
    - name: ADRESSEREGISTER_URL
      value: "https://ws.test.nhn.no/v1/AR/Basic"
