apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fastlegerest
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: fastlegerest/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: fastlegerest/internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: fastlegerest/internal/prometheus
  ingresses:
    - "https://fastlegerest.dev.intern.nav.no"
    - "https://fastlegerest.dev-fss-pub.nais.io"
    - "https://fastlegerest.nais.preprod.local"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://fastlegerest.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/dev/srvfastlegerest"
        mountPath: "/secrets/serviceuser/fastlegerest"
      - kvPath: "/kv/preprod/fss/fastlegerest/default"
        mountPath: "/secrets/vault"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: '443'
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: 'true'
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: EKSTERN_HELSE_FASTLEGEINFORMASJON_URL
      value: https://pep-gw-q4.oera-q.local:9443/ekstern/helse/fastlegeinformasjon
    - name: EKSTERN_HELSE_ADRESSEREGISTERET_V1_URL
      value: https://pep-gw-q4.oera-q.local:9443/ekstern/helse/adresseregisteret/v1
    - name: PARTNER_WS_URL
      value: https://wasapp-q1.adeo.no/emottak-partnerweb/partnerService/
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_DISCOVERYURL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_ACCEPTEDAUDIENCE
      value: srvsyfooppfolgings
    - name: SYFOPARTNERINFO_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfopartnerinfo"
    - name: SYFOPARTNERINFO_URL
      value: "https://syfopartnerinfo.nais.preprod.local"
    - name: PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: PDL_URL
      value: https://pdl-api.dev.intern.nav.no/graphql
    - name: ISDIALOGMELDING_IDENTIFIER
      value: dev-gcp.teamsykefravr.isdialogmelding
    - name: ISDIALOGMELDING_URL
      value: https://isdialogmelding.dev.intern.nav.no
