server:
  servlet:
    context-path: /fastlegerest

no.nav.security.jwt:
  issuers: selvbetjening,veileder,veilederaad
  issuer:
    selvbetjening:
      discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
      accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
      cookie_name: selvbetjening-idtoken
    sts:
      discoveryurl: <naiserator>
      accepted_audience: <naiserator>
    veileder:
      discoveryurl: <syfonais>
      accepted_audience: <syfonais>
      cookie_name: isso-idtoken
    veilederaad:
      discoveryurl: <nais-manifest>
      accepted_audience: <nais-manifest>
      cookiename: ID_token

local_mock: false

spring:
  profiles.active: remote
  main.banner-mode: 'off'
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

logging.config: classpath:logback-spring.xml
