server:
  servlet:
    context-path: /fastlegerest

no.nav.security.jwt:
  issuers: selvbetjening,veilederaad
  issuer:
    selvbetjening:
      discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
      accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
      cookie_name: selvbetjening-idtoken
    veilederaad:
      discoveryurl: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
      cookiename: ID_token

spring:
  profiles.active: remote
  main.banner-mode: 'off'
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

logging.config: classpath:logback-spring.xml
